name: Build Cards Project

on:
  push:
    paths:
      - 'packages/cards/**'
  pull_request:
    paths:
      - 'packages/cards/**'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

  build-shared:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache Node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Build Shared
        run: yarn workspace shared build

  test-cards:
    needs: build-shared
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Test Cards
        run: yarn workspace cards test

  build-cards:
    needs: test-cards
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Build Cards
        run: yarn workspace cards build

      - name: Copy files to a temporary directory
        run: |
          mkdir cards
          cp -R packages/cards/dist/* cards/

  deploy:
    needs: build-cards
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: 138.68.115.124
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'cards/*'
          target: '/usr/share/nginx/html/microfrontend/apps'
