name: Build Hosts Project

on:
  push:
    paths:
      - 'packages/hosts/**'
  pull_request:
    paths:
      - 'packages/hosts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn install

      - name: Build Hosts
        run: yarn workspace hosts build

      - name: Copy files to a temporary directory
        run: |
          mkdir hosts
          cp -R packages/hosts/dist/* hosts/

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: 138.68.115.124
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "hosts/*"
          target: "/usr/share/nginx/html/microfrontend/apps"
